openapi: 3.0.0
info:
  title: Translation Service API
  version: 1.0.0
  description: API for translation services
servers:
  - url: http://127.0.0.1:8888
    description: Local development server
paths:
  /service_run_stream:
    post:
      summary: Run a translation service
      operationId: runTranslationService
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - service_id
                - params
              properties:
                service_id:
                  type: string
                  description: Service identifier
                params:
                  type: object
                  required:
                    - source_lang
                    - target_lang
                    - source_text
                  properties:
                    source_lang:
                      type: string
                      description: Source language
                    target_lang:
                      type: string
                      description: Target language
                    source_text:
                      type: string
                      description: Text to translate
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: string
                    description: Translated text
        '400':
          description: Bad request
        '500':
          description: Internal server error
